# =============================================================================
# RVAMS Settings
# =============================================================================
[database]
url = "hebe.db"

[log]
level = "INFO"
json_output = false
ansi_color = false 
